#!/bin/bash
# after cleaning the harddrive, was getting problem
# with ImportErrors. 
# installing python 3.10 and libffi 3.3 fixed the problem


ENVNAME=fix4
conda create --name $ENVNAME
conda activate $ENVNAME
conda install libffi==3.3
conda install python==3.10
conda install pip
python -m pip install -r requires.txt
make clean
make all

conda install ipykernel
python -m ipykernel install --user --name myenv --display-name "Python (myenv)"
#ipython kernel install --user --name=$ENVNAME
