#!/bin/bash
# after cleaning the harddrive, was getting problem
# with ImportErrors. 
# installing python 3.10 and libffi 3.3 fixed the problem


ENVNAME=clean_env
conda create --name $ENVNAME
conda activate $ENVNAME
conda install libffi==3.3
conda install python==3.10
conda install pip
python -m pip install -r requirements.txt
make clean
make all

conda install ipykernel
python -m ipykernel install --user --name $ENVNAME --display-name "Python ${ENVNAME}"
#ipython kernel install --user --name=$ENVNAME
