#!/bin/bash
# after cleaning the harddrive, was getting problem
# with ImportErrors. 
# installing python 3.10 and libffi 3.3 fixed the problem

conda create --name fix4
conda activate fix4
conda install libffi==3.3
conda install python==3.10
conda install pip
python -m pip install -r requires.txt
make clean
make all
